import BoxReveal from "../BoxReveal/BoxReveal";


const Projects = () => {
    return (
        <div className="lg:max-w-[1400px] mx-auto mt-20 shadow-lg  shadow-green-400">
             <h1 className="text-center text-white font-bold   ml-[50px] md:ml-[300px] lg:ml-[600px] justify-center text-4xl btn btn-outline border-0 border-b-4 border-green-400   shadow-sm shadow-green-400 mt-7 mb-8">My Projects</h1>
          <div className="carousel w-full">
  <div id="item1" className="carousel-item  w-full">
    <div className="text-center mx-auto text-white p-5">
    <BoxReveal boxColor={"#4ade80"} duration={0.5}> <h1 className="text-center text-2xl mx-auto font-bold text-green-400">Project Title: Online Book Shop Management System</h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}>  <h1 className="text-center text-2xl mt-6 mx-auto text-green-400 ">Description:</h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}>  <h1 className="mt-2 text-slate-300">I developed an Online Book Shop Management System in C language, designed to efficiently manage and streamline bookshop operations for both administrators and users. The system features a comprehensive admin section, secured by a password, which allows administrators to add, delete, and update details about books. These details include book name, book ID, author, genre, quantity, publication name, and price. This robust functionality ensures that the book inventory is always current and accurate.</h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}> <h1 className="mt-2 text-slate-300">Additionally, the system provides a user-friendly interface for customers, enabling them to search for books by various criteria such as name, ID, author, publication, and genre. Once a book is found, users can purchase their desired books, with the system automatically calculating and displaying the total price for their selection.</h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}> <h1 className="mt-2 text-slate-300">This project not only facilitates efficient book management but also enhances the shopping experience for users by providing easy navigation and comprehensive search capabilities. The integration of secure admin access ensures that only authorized personnel can modify book details, thereby maintaining the integrity of the bookshop's inventory. Overall, this system exemplifies the effective use of C programming to create a practical and user-centric application for bookshop management.</h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}> <h1 className="text-2xl mt-5 text-green-400">Outcome</h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">1.Functional System Development:<span className="text-slate-300"> Successfully developed a comprehensive Online Book Shop Management System using the C programming language, demonstrating proficiency in creating a robust software application. </span></h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}>  <h2 className="text-left m-2">2.Secure Admin Access:<span className="text-slate-300"> Implemented a secure password-protected admin section, ensuring that only authorized personnel can add, delete, or update book information, thereby maintaining the integrity and security of the system.</span></h2></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">3.Efficient Inventory Management:<span className="text-slate-300"> Enabled efficient management of book inventory with functionalities to add, delete, and update book details such as name, ID, author, genre, quantity, publication, and price, ensuring an up-to-date and accurate inventory.</span></h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}><h3 className="text-left m-2">4.Enhanced User Experience:<span className="text-slate-300"> Created a user-friendly interface that allows customers to search for books by various criteria (name, ID, author, publication, genre), improving the ease and efficiency of finding desired books.</span></h3></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}><h2 className="text-left m-2">5.Streamlined Purchasing Process:<span className="text-slate-300"> Developed a purchasing module for users to buy books, with the system automatically calculating and displaying the total price, simplifying the buying process and enhancing user satisfaction.</span></h2></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">6.Comprehensive Search Capabilities:<span className="text-slate-300">  Implemented robust search functionalities for both admin and user sections, allowing quick and precise retrieval of book information based on multiple search parameters.</span></h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}><h2 className="text-left m-2">7.Real-World Application:<span className="text-slate-300">  Demonstrated the practical application of C programming in developing a real-world project that addresses the needs of bookshop management and customer service.</span></h2></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}><h5 className="text-left m-2">8.Technical Skill Enhancement:<span className="text-slate-300"> Enhanced technical skills in C programming, data management, and user interface design through the development and implementation of the project.</span></h5></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">10.Positive User Feedback:<span className="text-slate-300">  Received positive feedback from initial users regarding the system's usability, search capabilities, and the overall shopping experience, validating the effectiveness of the project.</span></h1></BoxReveal>
    <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">11.Documentation and Presentation: <span className="text-slate-300">Successfully documented the project development process and presented the final system, showcasing the ability to communicate technical information clearly and effectively</span></h1></BoxReveal>
   </div>

  </div>
  <div id="item2" className="carousel-item w-full">
  <div className="text-center mx-auto text-white p-5">
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-center text-2xl mx-auto font-bold text-green-400">Project Title: Stopwatch and Timer   </h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-center text-2xl mt-6 mx-auto text-green-400 ">Description:</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="mt-2 text-slate-300">I developed a Stopwatch and Timer application in C, designed to offer flexible timing functionalities for various purposes. This project allows users to input a specific time duration, after which the stopwatch automatically starts counting down. Users can initiate the timer, and the application displays real-time countdown updates until the specified time elapses. Once the timer reaches zero, the application notifies the user with a message indicating "time over," effectively halting the stopwatch operation.</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="mt-2 text-slate-300">The project leverages fundamental C programming concepts to manage time calculations and user interactions seamlessly. It includes features such as input validation to ensure accurate time inputs and robust error handling to manage unexpected scenarios. The user interface is designed to be intuitive, providing clear prompts and feedback throughout the timing process.</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="mt-2 text-slate-300">This Stopwatch and Timer application serves as a practical tool for various timing needs, from simple countdowns for tasks and activities to more structured time management in educational or professional settings. It not only showcases proficiency in C programming but also demonstrates the ability to develop functional and user-friendly software applications. Overall, this project exemplifies the utility of programming skills in creating efficient and reliable digital tools for everyday use..</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-2xl mt-5 text-green-400">Outcome</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">1.Functional Stopwatch and Timer Implementation:<span className="text-slate-300"> Successfully developed a functional Stopwatch and Timer application in C, demonstrating proficiency in programming logic and time management algorithms. </span></h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h2 className="text-left m-2">2.Flexible Time Input Handling:<span className="text-slate-300"> Implemented robust input handling for user-defined time durations, ensuring accurate and reliable countdown functionality based on user specifications.</span></h2></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">3.Real-Time Countdown Display:<span className="text-slate-300"> Created a user interface that displays real-time countdown updates during the timing process, providing clear and intuitive feedback to the user.</span></h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}> <h3 className="text-left m-2">4.Accurate Time Management:<span className="text-slate-300"> Achieved precise time management capabilities with the application accurately tracking and displaying elapsed time until completion, enhancing its usability and reliability.</span></h3></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h2 className="text-left m-2">5.Error Handling and Validation:<span className="text-slate-300"> Incorporated effective error handling mechanisms to manage unexpected inputs or system interruptions, ensuring smooth operation throughout the countdown process.</span></h2></BoxReveal> 
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">6.User-Friendly Interface:<span className="text-slate-300">  Designed an intuitive user interface with prompts and messages that guide users through setting, starting, and completing timed tasks, enhancing overall user experience</span></h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h2 className="text-left m-2">7.Educational and Practical Utility:<span className="text-slate-300"> Demonstrated the practical application of C programming in developing a tool suitable for various timing needs, from personal productivity tasks to educational exercises..</span></h2></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}> <h5 className="text-left m-2">8.Technical Skill Enhancement: <span className="text-slate-300"> Enhanced proficiency in C programming, algorithm design, and user interface development through the project's implementation and iterative improvement process.</span></h5></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">10.Positive User Feedback:<span className="text-slate-300">  Received positive feedback from users on the application's functionality, ease of use, and reliability in managing timed activities, validating its effectiveness and practicality.</span></h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">11.Documentation and Presentation: <span className="text-slate-300">Successfully documented the project's development process, including detailed technical specifications and user instructions, and presented the final application, showcasing clear communication and project management skills.</span></h1></BoxReveal>
   </div>
  </div>
  <div id="item3" className="carousel-item w-full">
  <div className="text-center mx-auto text-white p-5">
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-center text-2xl mx-auto font-bold text-green-400">Project Title: Online Teacher-Student Portal </h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-center text-2xl mt-6 mx-auto text-green-400 ">Description:</h1></BoxReveal> 
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="mt-2 text-slate-300">The Online Teacher-Student Portal project in C is a comprehensive system designed to facilitate efficient management and interaction between teachers and students. As an administrator, the portal allows me to securely access and manage student information through a password-protected admin section. This includes functionalities to add new student entries, delete existing student records, input and update student results, and display detailed information about each student. The system also features robust search capabilities, enabling quick retrieval of specific student details based on various criteria.</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}>  <h1 className="mt-2 text-slate-300">In addition to administrative functions, the portal provides a dedicated student section with four key features. Firstly, the "Live Result" feature allows students to access real-time updates on their academic performance. Secondly, the "Teacher Evaluation" module enables students to provide feedback on teaching quality and course experiences. The "Grade Check" option allows students to view their current grades and academic standing, providing transparency and accountability in their academic progress. Lastly, the "Waiver Check" functionality allows students to check eligibility and apply for course waivers based on predefined criteria.</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}> <h1 className="mt-2 text-slate-300">This project leverages core concepts of C programming to manage data storage, user authentication, and interactive functionalities effectively. It enhances educational administration by streamlining administrative tasks and empowering students with access to critical academic information and services through a user-friendly interface. Overall, the Online Teacher-Student Portal project exemplifies the integration of technology in education management, promoting transparency, efficiency, and engagement between educational stakeholders.

</h1></BoxReveal>
<BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-2xl mt-5 text-green-400">Outcome</h1></BoxReveal>
<BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">1.Comprehensive Administration Features: <span className="text-slate-300"> Successfully developed and implemented a robust admin section with secure login authentication, enabling efficient management of student records. Administrators can add, delete, update student information, and perform detailed searches, ensuring streamlined administrative processes. </span></h1></BoxReveal>
<BoxReveal boxColor={"#4ade80"} duration={0.5}><h2 className="text-left m-2">2.Enhanced Student Interaction:<span className="text-slate-300"> Implemented a user-friendly student section with features such as "Live Result" updates, "Teacher Evaluation" feedback submission, "Grade Check" for academic progress monitoring, and "Waiver Check" eligibility verification. These functionalities empower students with real-time information and interactive tools to manage their academic journey effectively.</span></h2></BoxReveal>
<BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">3.User-Friendly Interface: <span className="text-slate-300"> Designed an intuitive interface for both administrators and students, incorporating clear navigation and informative prompts to facilitate ease of use and enhance user experience..</span></h1></BoxReveal>
<BoxReveal boxColor={"#4ade80"} duration={0.5}><h3 className="text-left m-2">4.Educational Administrative Efficiency:<span className="text-slate-300"> Improved efficiency in educational administration by automating routine tasks and providing quick access to student records and academic data, thereby reducing administrative workload and improving operational efficiency.</span></h3></BoxReveal>
<BoxReveal boxColor={"#4ade80"} duration={0.5}><h2 className="text-left m-2">5.Positive User Feedback: <span className="text-slate-300"> Received positive feedback from users, including administrators and students, on the system's reliability, functionality, and user-friendliness. Users appreciated the ease of accessing and managing academic information through the portal.</span></h2></BoxReveal>
<BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">Technical Skill Advancement:<span className="text-slate-300"> Advanced skills in C programming, database management, and user interface design through the development and implementation phases of the project, contributing to professional growth and proficiency in software development.</span></h1></BoxReveal>
<BoxReveal boxColor={"#4ade80"} duration={0.5}><h2 className="text-left m-2">7.Documentation and Presentation:<span className="text-slate-300">  Successfully documented the project's specifications, development process, and user instructions, ensuring clear communication of project details and functionalities. Presented the final product effectively, demonstrating thorough understanding and presentation skills.</span></h2></BoxReveal>

   </div>
  </div>
  <div id="item4" className="carousel-item w-full">
  <div className="text-center mx-auto text-white p-5">
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-center text-2xl mx-auto font-bold text-green-400">Project Title: LED Dimmer Circuit </h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-center text-2xl mt-6 mx-auto text-green-400 ">Description:</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="mt-2 text-slate-300">An LED dimmer circuit allows you to adjust the brightness of an LED or a group of LEDs. This is achieved by controlling the amount of current flowing through the LEDs. The circuit typically consists of a variable resistor (potentiometer) or a Pulse Width Modulation (PWM) controller, which modulates the power delivered to the LEDs. In a simple potentiometer-based dimmer, adjusting the resistance changes the voltage across the LEDs, thereby varying their brightness. In a PWM-based dimmer, the circuit rapidly switches the LED on and off at a high frequency, controlling the average power and hence the brightness. This method is more efficient and provides smoother dimming compared to variable resistance dimming. LED dimmer circuits are commonly used in lighting applications, providing energy savings and extending the lifespan of LEDs by reducing their operating current.</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-2xl mt-5 text-green-400">Outcome</h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">1.Successful Implementation:<span className="text-slate-300"> The LED dimmer circuit was successfully designed and implemented, demonstrating smooth and precise control of LED brightness. </span></h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}> <h2 className="text-left m-2">2. Efficiency:<span className="text-slate-300">  By using Pulse Width Modulation (PWM) technology, the circuit achieved high efficiency, with minimal power loss compared to traditional dimming methods.</span></h2></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">3. User Control: <span className="text-slate-300"> The project provided an intuitive user interface for adjusting brightness levels, ensuring ease of use and a high degree of control over the lighting environment.</span></h1></BoxReveal> 
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h3 className="text-left m-2">4. Extended LED Lifespan:<span className="text-slate-300">The circuit effectively managed current flow to the LEDs, helping to extend their operational lifespan by preventing overheating and overcurrent.</span></h3></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}> <h2 className="text-left m-2">5.Energy Savings:<span className="text-slate-300">The dimming capability allowed for significant energy savings by reducing power consumption when full brightness was not needed.</span></h2></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">6. Versatility: <span className="text-slate-300">  The circuit was versatile and adaptable, suitable for a wide range of applications from residential lighting to commercial displays.</span></h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h2 className="text-left m-2">7. Cost-Effective Solution:<span className="text-slate-300">  The project resulted in a cost-effective dimming solution that can be replicated and scaled for various LED lighting systems.</span></h2></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h5 className="text-left m-2">8. Technical Learning:<span className="text-slate-300"> The project provided valuable hands-on experience with electronic components, circuit design, and PWM technology, enhancing our technical skills and knowledge</span></h5></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">10.Positive Feedback:<span className="text-slate-300">  Initial testing and feedback from users indicated high satisfaction with the dimming performance and ease of operation, validating the project's success.</span></h1></BoxReveal>
  <BoxReveal boxColor={"#4ade80"} duration={0.5}><h1 className="text-left m-2">11. Documentation and Presentation: <span className="text-slate-300">Comprehensive documentation and a professional presentation of the project were completed, showcasing our ability to communicate technical achievements effectively.</span></h1></BoxReveal>
   </div>
  </div>
</div>
<div className="flex w-full justify-center gap-2 py-2">
  <a href="#item1" className="btn btn-xs">1</a>
  <a href="#item2" className="btn btn-xs">2</a>
  <a href="#item3" className="btn btn-xs">3</a>
  <a href="#item4" className="btn btn-xs">4</a>
</div>
        </div>
    );
};

export default Projects;